package main

import (
	"fmt"
	"strings"
	"time"
)

// correctionsMarker is the boundary between what --reflect generates and what
// the learner owns. Everything from this line down survives regeneration
// byte-for-byte (#17 D3).
const correctionsMarker = "## Corrections"

// modelMeta is what the frontmatter states about the run that produced the file:
// when, over what window, and by which model.
//
// Separate from learnerModel because it is provenance rather than a claim —
// nothing here is inferred, so nothing here needs evidence.
type modelMeta struct {
	Updated   time.Time
	From, To  time.Time
	Lookups   int
	Questions int
	Model     string
}

// renderUserModel writes everything ABOVE the corrections marker.
//
// Pure: a struct in, a string out. That is what lets the golden be the file a
// person would be handed rather than a fixture assembled for a test.
//
// A dropped claim renders as NOTHING, never as an empty section. An empty
// "## Level" says there is a level and it is blank, which is a different claim
// from "nothing was inferred" — the same distinction #16's prompt sections draw,
// and the one that makes a generic answer sound confident.
func renderUserModel(m learnerModel, meta modelMeta) string {
	var b strings.Builder

	b.WriteString("---\n")
	b.WriteString("type: user-model\n")
	fmt.Fprintf(&b, "updated: %s\n", meta.Updated.Format("2006-01-02"))
	fmt.Fprintf(&b, "window: %s..%s          # %d lookups, %d questions\n",
		dateOrNone(meta.From), dateOrNone(meta.To), meta.Lookups, meta.Questions)
	fmt.Fprintf(&b, "generated_by: define --reflect (%s)\n", meta.Model)
	b.WriteString("---\n\n")

	b.WriteString("<!-- Everything above ## Corrections is regenerated by `define --reflect`.\n")
	b.WriteString("     Everything below it is yours and is never rewritten. -->\n\n")

	if m.Level.Band != "" {
		b.WriteString("## Level\n\n")
		fmt.Fprintf(&b, "**%s** — %s\n\n", m.Level.Band, m.Level.Rationale)
		fmt.Fprintf(&b, "Read off: %s.\n\n", joinWords(m.Level.Evidence))
	}

	if len(m.Domains) > 0 {
		b.WriteString("## Domains they read in\n\n")
		b.WriteString("Inferred from what gets looked up — never asked.\n\n")
		b.WriteString("| domain | share | read off | what to do about it |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, d := range m.Domains {
			fmt.Fprintf(&b, "| %s | %.0f%% | %s | %s |\n",
				d.Name, d.Share*100, joinWords(d.Evidence), d.Directive)
		}
		b.WriteString("\n")
	}

	b.WriteString(correctionsMarker + "\n\n")
	b.WriteString("Yours. Disagree here and it sticks — a correction outranks anything\n")
	b.WriteString("inferred above, and `--reflect` will not touch this section again.\n")
	return b.String()
}

// dateOrNone keeps an empty window honest: a zero time formats as year 1, which
// would read as a real date nobody could explain.
func dateOrNone(t time.Time) string {
	if t.IsZero() {
		return "none"
	}
	return t.Format("2006-01-02")
}

// joinWords renders evidence as backticked words, so a reader can see at a
// glance that a claim is naming deck entries rather than describing them.
func joinWords(words []string) string {
	quoted := make([]string, 0, len(words))
	for _, w := range words {
		quoted = append(quoted, "`"+w+"`")
	}
	return strings.Join(quoted, ", ")
}
